In [30]:
import pandas as pd

In [36]:
data = {"name": ["a", "b", "c", "d", "a", "c"], "eng": [8, 7, 5, 8, 8, 5], "hindi": [2, 3, 4, 5, 2, 6]}

In [46]:
df = pd.DataFrame(data)
df

  name  eng  hindi
0    a    8      2
1    b    7      3
2    c    5      4
3    d    8      5
4    a    8      2
5    c    5      6

In [47]:
df.duplicated().sum()

np.int64(1)

In [48]:
df.shape

(6, 3)

In [49]:
df.size

18

In [50]:
df = df.drop_duplicates()
df

  name  eng  hindi
0    a    8      2
1    b    7      3
2    c    5      4
3    d    8      5
5    c    5      6

In [51]:
df.shape

(5, 3)